version: "2"
services:
  mongo:
    image: mongo:3
    container_name: mongo
    privileged: true
    restart: always
    networks:
      - yapi
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yapi
      - MONGO_INITDB_ROOT_PASSWORD=yapi
      - MONGO_INITDB_DATABASE=yapi
    volumes:
      - ./mongo-data:/data/db
  yapi:
    build: .
    container_name: yapi
    privileged: true
    restart: always
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    networks:
      - yapi
    volumes:
      - ./config.json:/app/config.json
      - ./yapi-runtime:/app/runtime
      - ../yapi:/home/vendors
networks:
  yapi:
